5. A survey was conducted among 2800 customers on several demographic characteristics. Working status, sex, age, age-group, race, happiness, no. of child, marital status, educational qualifications, income group etc. had been captured for that purpose. (Data set: sample_survey.csv).
a. Is there any relationship in between labour force status with marital status?
b. Do you think educational qualification is somehow controlling the marital status?
c. Is happiness is driven by earnings or marital status?

In [1]:
import pandas as pd
from scipy import stats
data=pd.read_csv(r'C:\siddharth\MCL\analytix\7. Basic Stats - Case Study-1\sample_survey.csv')

In [19]:
labor=data['wrkstat']
marital=data['marital']
education=data['degree']
happiness=data['happy']
earning=data['income']

In [20]:
p1=pd.crosstab(labor,marital)
p2=pd.crosstab(education,marital)
p3=pd.crosstab(happiness,marital)
p4=pd.crosstab(happiness,earning)

In [17]:
stats.chi2_contingency(observed=p1)

(729.2421426572284,
 1.4875268409067568e-135,
 28,
 array([[ 51.69187279, 155.8869258 ,  76.84240283,  10.77879859,
          32.8       ],
        [  8.51024735,  25.66431095,  12.65088339,   1.7745583 ,
           5.4       ],
        [ 62.09328622, 187.25441696,  92.30459364,  12.94770318,
          39.4       ],
        [ 12.45017668,  37.5459364 ,  18.50777385,   2.59611307,
           7.9       ],
        [  7.24946996,  21.86219081,  10.77667845,   1.51166078,
           4.6       ],
        [  9.14063604,  27.56537102,  13.58798587,   1.90600707,
           5.8       ],
        [246.95477032, 744.74028269, 367.10989399,  51.495053  ,
         156.7       ],
        [ 47.90954064, 144.48056537,  71.21978799,   9.99010601,
          30.4       ]]))

In [21]:
stats.chi2_contingency(observed=p2)

(122.68449020508541,
 1.6707923432360119e-18,
 16,
 array([[ 75.06345268, 227.39312301, 111.83268345,  15.75824176,
          47.95249911],
        [ 32.19248493,  97.52215526,  47.9617157 ,   6.75824176,
          20.56540234],
        [235.55476781, 713.57674583, 350.9393832 ,  49.45054945,
         150.4785537 ],
        [ 32.66359447,  98.94930876,  48.66359447,   6.85714286,
          20.86635945],
        [ 67.52570011, 204.55866714, 100.60262318,  14.17582418,
          43.1371854 ]]))

In [ ]:
pvalue < significant value
>> marital status is not driven by education

In [22]:
stats.chi2_contingency(observed=p3)

(260.6894389418282,
 9.3147261197964e-52,
 8,
 array([[ 53.6969697 , 162.06060606,  79.27272727,  11.15151515,
          33.81818182],
        [248.58538324, 750.24527629, 366.98609626,  51.62495544,
         156.55828877],
        [140.71764706, 424.69411765, 207.74117647,  29.22352941,
          88.62352941]]))

In [23]:
stats.chi2_contingency(observed=p4)

(178.9505306121643,
 1.4107677273473057e-26,
 22,
 array([[  3.89520355,  23.12777106,  21.66706973,  29.82265216,
         191.35187424,   2.92140266,   3.89520355,   4.26037888,
           4.01692866,   5.72108021,   7.06005643,   4.26037888],
        [ 18.16041919, 107.82748892, 101.01733172, 139.04070939,
         892.1305925 ,  13.62031439,  18.16041919,  19.86295848,
          18.72793229,  26.67311568,  32.91575977,  19.86295848],
        [  9.94437727,  59.04474002,  55.31559855,  76.13663845,
         488.51753325,   7.45828295,   9.94437727,  10.87666264,
          10.25513906,  14.60580411,  18.0241838 ,  10.87666264]]))

p1=pd.crosstab(labor,marital)
p2=pd.crosstab(education,marital)
p3=pd.crosstab(happiness,marital)
p4=pd.crosstab(happiness,earning)

> for all pvalue < significant value
> so all are independent and not controlling anything.